//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BusinessObjects", "FK_MenuAndPages_ParentId_MenuAndPages_Id", "MenuAndPages", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BusinessObjects.MenuAndPage), "MenuAndPages1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusinessObjects.MenuAndPage))]
[assembly: EdmRelationshipAttribute("BusinessObjects", "FK_News_0", "NewsCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BusinessObjects.NewsCategory), "News", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BusinessObjects.News))]

#endregion

namespace BusinessObjects
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModelEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModelEntities object using the connection string found in the 'ModelEntities' section of the application configuration file.
        /// </summary>
        public ModelEntities() : base("name=ModelEntities", "ModelEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelEntities object.
        /// </summary>
        public ModelEntities(string connectionString) : base(connectionString, "ModelEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelEntities object.
        /// </summary>
        public ModelEntities(EntityConnection connection) : base(connection, "ModelEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Banner> Banners
        {
            get
            {
                if ((_Banners == null))
                {
                    _Banners = base.CreateObjectSet<Banner>("Banners");
                }
                return _Banners;
            }
        }
        private ObjectSet<Banner> _Banners;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MenuAndPage> MenuAndPages
        {
            get
            {
                if ((_MenuAndPages == null))
                {
                    _MenuAndPages = base.CreateObjectSet<MenuAndPage>("MenuAndPages");
                }
                return _MenuAndPages;
            }
        }
        private ObjectSet<MenuAndPage> _MenuAndPages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<News> News
        {
            get
            {
                if ((_News == null))
                {
                    _News = base.CreateObjectSet<News>("News");
                }
                return _News;
            }
        }
        private ObjectSet<News> _News;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NewsCategory> NewsCategories
        {
            get
            {
                if ((_NewsCategories == null))
                {
                    _NewsCategories = base.CreateObjectSet<NewsCategory>("NewsCategories");
                }
                return _NewsCategories;
            }
        }
        private ObjectSet<NewsCategory> _NewsCategories;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Banners EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBanners(Banner banner)
        {
            base.AddObject("Banners", banner);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MenuAndPages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenuAndPages(MenuAndPage menuAndPage)
        {
            base.AddObject("MenuAndPages", menuAndPage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the News EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNews(News news)
        {
            base.AddObject("News", news);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NewsCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNewsCategories(NewsCategory newsCategory)
        {
            base.AddObject("NewsCategories", newsCategory);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusinessObjects", Name="Banner")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Banner : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Banner object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="link">Initial value of the Link property.</param>
        /// <param name="picture">Initial value of the Picture property.</param>
        public static Banner CreateBanner(global::System.Int32 id, global::System.String title, global::System.String link, global::System.String picture)
        {
            Banner banner = new Banner();
            banner.Id = id;
            banner.Title = title;
            banner.Link = link;
            banner.Picture = picture;
            return banner;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsOuter
        {
            get
            {
                return _IsOuter;
            }
            set
            {
                OnIsOuterChanging(value);
                ReportPropertyChanging("IsOuter");
                _IsOuter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsOuter");
                OnIsOuterChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsOuter;
        partial void OnIsOuterChanging(Nullable<global::System.Boolean> value);
        partial void OnIsOuterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.String _Picture;
        partial void OnPictureChanging(global::System.String value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _SortOrder;
        partial void OnSortOrderChanging(Nullable<global::System.Int32> value);
        partial void OnSortOrderChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusinessObjects", Name="MenuAndPage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MenuAndPage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MenuAndPage object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="showInTopMenu">Initial value of the ShowInTopMenu property.</param>
        /// <param name="handler">Initial value of the Handler property.</param>
        public static MenuAndPage CreateMenuAndPage(global::System.Int32 id, global::System.String title, global::System.Boolean showInTopMenu, global::System.String handler)
        {
            MenuAndPage menuAndPage = new MenuAndPage();
            menuAndPage.Id = id;
            menuAndPage.Title = title;
            menuAndPage.ShowInTopMenu = showInTopMenu;
            menuAndPage.Handler = handler;
            return menuAndPage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShowInTopMenu
        {
            get
            {
                return _ShowInTopMenu;
            }
            set
            {
                OnShowInTopMenuChanging(value);
                ReportPropertyChanging("ShowInTopMenu");
                _ShowInTopMenu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowInTopMenu");
                OnShowInTopMenuChanged();
            }
        }
        private global::System.Boolean _ShowInTopMenu;
        partial void OnShowInTopMenuChanging(global::System.Boolean value);
        partial void OnShowInTopMenuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MenuSortOrder
        {
            get
            {
                return _MenuSortOrder;
            }
            set
            {
                OnMenuSortOrderChanging(value);
                ReportPropertyChanging("MenuSortOrder");
                _MenuSortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MenuSortOrder");
                OnMenuSortOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _MenuSortOrder;
        partial void OnMenuSortOrderChanging(Nullable<global::System.Int32> value);
        partial void OnMenuSortOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Handler
        {
            get
            {
                return _Handler;
            }
            set
            {
                OnHandlerChanging(value);
                ReportPropertyChanging("Handler");
                _Handler = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Handler");
                OnHandlerChanged();
            }
        }
        private global::System.String _Handler;
        partial void OnHandlerChanging(global::System.String value);
        partial void OnHandlerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusinessObjects", "FK_MenuAndPages_ParentId_MenuAndPages_Id", "MenuAndPages1")]
        public EntityCollection<MenuAndPage> SubPages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MenuAndPage>("BusinessObjects.FK_MenuAndPages_ParentId_MenuAndPages_Id", "MenuAndPages1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MenuAndPage>("BusinessObjects.FK_MenuAndPages_ParentId_MenuAndPages_Id", "MenuAndPages1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusinessObjects", "FK_MenuAndPages_ParentId_MenuAndPages_Id", "MenuAndPages")]
        public MenuAndPage ParentPage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuAndPage>("BusinessObjects.FK_MenuAndPages_ParentId_MenuAndPages_Id", "MenuAndPages").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuAndPage>("BusinessObjects.FK_MenuAndPages_ParentId_MenuAndPages_Id", "MenuAndPages").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MenuAndPage> ParentPageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuAndPage>("BusinessObjects.FK_MenuAndPages_ParentId_MenuAndPages_Id", "MenuAndPages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MenuAndPage>("BusinessObjects.FK_MenuAndPages_ParentId_MenuAndPages_Id", "MenuAndPages", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusinessObjects", Name="News")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class News : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new News object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        public static News CreateNews(global::System.Int32 id, global::System.String title, global::System.DateTime date, global::System.String text)
        {
            News news = new News();
            news.Id = id;
            news.Title = title;
            news.Date = date;
            news.Text = text;
            return news;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusinessObjects", "FK_News_0", "NewsCategories")]
        public NewsCategory NewsCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NewsCategory>("BusinessObjects.FK_News_0", "NewsCategories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NewsCategory>("BusinessObjects.FK_News_0", "NewsCategories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NewsCategory> NewsCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NewsCategory>("BusinessObjects.FK_News_0", "NewsCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NewsCategory>("BusinessObjects.FK_News_0", "NewsCategories", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BusinessObjects", Name="NewsCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NewsCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NewsCategory object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        public static NewsCategory CreateNewsCategory(global::System.Int32 id, global::System.String title)
        {
            NewsCategory newsCategory = new NewsCategory();
            newsCategory.Id = id;
            newsCategory.Title = title;
            return newsCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BusinessObjects", "FK_News_0", "News")]
        public EntityCollection<News> News
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<News>("BusinessObjects.FK_News_0", "News");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<News>("BusinessObjects.FK_News_0", "News", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
